### ISSUE TITLE
The sub-menu items are not shown when I click it

### ISSUE THREAD

**Issue by hyeonchang** [jothepro/doxygen-awesome-css#104]
I have a question why are the sub-menu items on the tree view not shown when I click them?

for example, the sub-menu items are shown (expanded) when I click the `Installations` like below.
<img width="334" alt="image" src="https://user-images.githubusercontent.com/1412931/209072489-9a15d6a7-ed6c-4217-962a-12a02bc571b2.png">

however, if I click the `Extensions` the sub-menu items are not shown (collapsed) like below.
<img width="324" alt="image" src="https://user-images.githubusercontent.com/1412931/209072979-0ef6094e-0e11-4a07-a9b4-abf096f7b755.png">
 
I have the same problem with my project.

Is there any solution to resolve the problem?

**Comment by jothepro** [comment]
Hm, that is interesting, I never noticed it. I doubt that I can answer your question though, the theme does just alter the looks of the navigation, not the behaviour. I think you should seek for help at [doxygen/doxygen](https://github.com/doxygen/doxygen).

**Comment by jothepro** [comment]
I am closing this issue since it IMO is out of the scope of this custom CSS. Feel free to reopen if you disagree!
