### ISSUE TITLE
Doxygen 1.9.6 support?

### ISSUE THREAD

**Issue by tim-gromeyer** [jothepro/doxygen-awesome-css#105]
Hello, doxygen 1.9.6 has just been released. I wanted to know how it is with compatibility. 1.9.5 was not supported due to a problem that was fixed in 1.9.6. **Merry Christmas** and a **happy new year**! Take your time with the development.

**Comment by jothepro** [comment]
The theme seems to work great with doxygen 1.9.6! I'll update the documentation accordingly.

If you encounter any issues as an early adopter, pls let me know!

Happy new year! ✨

**Comment by tim-gromeyer** [comment]
I found a "bug". When you try to disable dark mode doxygens dark mode is still active. You can work around it by changing the `HTML_COLORSTYLE` variable to `TOGGLE`. Would be good to mention this in the README.

**Comment by miguno** [comment]
Same bug here. The workaround in https://github.com/jothepro/doxygen-awesome-css/issues/105#issuecomment-1380537133 works for me, too.

**Comment by jothepro** [comment]
Doxygen 1.9.6 is now officially supported in the latest release [v2.2.0](https://github.com/jothepro/doxygen-awesome-css/releases/tag/v2.2.0).

I've added documentation on how to configure it properly [here](https://jothepro.github.io/doxygen-awesome-css/index.html#autotoc_md11).
