### ISSUE TITLE
Easiest way to move the detail description of a class to the top?

### ISSUE THREAD

**Issue by Becheler** [jothepro/doxygen-awesome-css#111]
Hi @jothepro ! 😸 
When documenting a class, I would like the @details section to show just after the @brief section (instead of having it at the very end of the page). I know I can mess up the doxygen layout by generating a template file controlling the layout of the generated documentation with `doxygen -l layoutFileName.xml` (see details [here](https://stackoverflow.com/questions/19831837/documenting-with-doxygen-put-details-on-top)) but I am worried it could mess doxygen-awesome in an unforeseen way?

**Comment by jothepro** [comment]
I cannot give you advice about that, I never tried it. Can you let me know in case it comes with unwanted side effects?
I don't think there is another way to move the section without editing the layout file, but I am not an expert on that.

**Comment by jothepro** [comment]
Closing this issue for now.
Please re-open if there are any learnings that you would like to share or if you had problems with the CSS when changing the layout.
