### ISSUE TITLE
Sidebar gets lost (unreachable) when reduced to minimum size

### ISSUE THREAD

**Issue by manzerbredes** [jothepro/doxygen-awesome-css#115]
Hello,
here is the problem:
![ezgif com-crop](https://github.com/jothepro/doxygen-awesome-css/assets/40263184/074c7629-1215-4c98-a40f-cd22b4b37c43)
At some point, by mistake, I resized the sidebar to its minimum size.
Problem is, I am not having access to the sidebar anymore with the mouse pointer. Even after refreshing the web page (due to the web browser cache I believe). Maybe having a minimum size for the sidebar can solve the problem?
Thank you for the great work.

**Comment by narendra8088** [comment]
Are you used code boostrap or CSS any other language framework library add?

**Comment by jothepro** [comment]
I agree, this should not happen. Afaik in the original Doxygen the sidebar handle would have some width, so it cannot get stuck. A minimum sidebar width would be a good workaround :+1:.

This should fix it for now:

```css
#side-nav {
  min-width: 45px;
}
```

I'll try to provide an official fix soon.
