### ISSUE TITLE
sidebar rendered with wrong indent width

### ISSUE THREAD

**Issue by GJCav** [jothepro/doxygen-awesome-css#121]
I am working on a doxygen template repo and using doxygen-awesome-css. But I find that after applying `doxygen-awesome-css/doxygen-awesome.css`, nested item in sidebar tree has wrong indent width.

![2023-07-09_12-12](https://github.com/jothepro/doxygen-awesome-css/assets/24679507/ebb38711-dd8b-4fca-b547-c599d5c74919)

I expect `Hello doxygen !` to be placed with more indent. After inspecting the element by edge developer tools, a `<span>` tag with class `arrow` is used as indent with proper width. But it is `display: inline` thus `width` has no effect.

![Screenshot from 2023-07-09 12-16-45](https://github.com/jothepro/doxygen-awesome-css/assets/24679507/d19089d2-fffa-4078-9d58-79d95f665003)

As the devtool suggests, applying the `display: inline-block` solves the problem.

![2023-07-09_12-21](https://github.com/jothepro/doxygen-awesome-css/assets/24679507/24a8b7bd-4d6f-4523-a08a-6c496b7d8fb1)

So please check if this is a bug or I break something down when installing doxygen-awesome.

Other information:

- doxygen: 1.9.7 (a2f34e1ed90f83713dc347b5134920f32c455d46)
- doxygen-awesome: v2.2.1

**Comment by jothepro** [comment]
I agree that the indentation on the screenshots that you provided doesn't look right. Can you provide a small example setup including the input file that the page was rendered from?

**Comment by GJCav** [comment]
emmmm.... a week later, I can't reproduce it either and doxygen-awesome-css works perfectly.

So I will close this issue and will reopen it if a stable reproducing method exists.

I truly appreciate your hard work and dedication to the project.
