### ISSUE TITLE
Note and warning text block colors are semantically misleading

### ISSUE THREAD

**Issue by dsieger** [jothepro/doxygen-awesome-css#123]
Ok now this is about details, but: I think the colors for the "Note" and "Warning" text boxes produced by the `\note` and `\warning` commands are semantically misleading.

Notes use orange, but in most other systems this defaults to some more neutral color like blue (like your "Todo" boxes). After all, a note is just that: something noteworthy. I want the reader to take note, but I don't want to alert him. No danger, no harm.

Similar, the "Warning" boxes probably should use orange to signify potential danger, whereas red should be reserved for something definitely bad, like bugs.

Just my 2 cents, feel free to close immediately.

**Comment by jothepro** [comment]
Tbh not a lot of thought has been going into the current coloring, so your 2 cents are welcome! 😋 Keeping this open a reminder that the colors could be improved.

**Comment by ilg-ul** [comment]
I also find the choice of colours unusual, even misleading. The other sites that I manage use a colour convention similar to the one suggested by @dsieger.
