### ISSUE TITLE
Please update the version in package.json for new releases!

### ISSUE THREAD

**Issue by ilg-ul** [jothepro/doxygen-awesome-css#130]
You just released 2.3.0, but the `package.json` version still reads 2.2.1, and so the package cannot be installed via npm/xpm.

Please be sure you update the version in package.json for new releases!

In this case you'll probably need to make a 2.3.1 release.

**Comment by ilg-ul** [comment]
FYI, the easiest way to keep everything in sync is to use `npm version`, it updates the package.json and adds the tag for the release.

In your case, in an up to date repository, all you have to do is `npm version patch`, then push everything.

**Comment by jothepro** [comment]
Thanks for pointing this out. Yeah I will need to adapt or improve my release workflow, otherwise this mistake is prone to happen again. I hope everything is working now?
