### ISSUE TITLE
Inconsistent font family in table of contents

### ISSUE THREAD

**Issue by dsieger** [jothepro/doxygen-awesome-css#131]
Doxygen (1.9.6) uses a different font family (Verdana) for the table of contents, as defined by the variable `--font-family-toc`. This is inconsistent with the system font stack used by doxygen-awesome-css. Would be nice to make this consistent.

I'm currently using a manual override, see [here](https://github.com/pmp-library/pmp-library/commit/a86d2a9944553d33795d5616bf78b2e2d4a15c68). However, I'm sure there's a better way to override the variable somewhere.

Thanks!

**Comment by jothepro** [comment]
Good catch, thx! I've applied your suggested fix!
