### ISSUE TITLE
Visual artifacts in nav tree with recent Doxygen versions

### ISSUE THREAD

**Issue by dsieger** [jothepro/doxygen-awesome-css#136]
I gave Doxygen 1.10.0 a try. There are some visual artifacts in the nav tree:

<img src="https://github.com/jothepro/doxygen-awesome-css/assets/6951585/bb629ba3-5daa-454f-b0f6-a9acf65a43a4" width=300>

Looks like the doxygen-awesome-css website is having some similar issues:

<img src="https://github.com/jothepro/doxygen-awesome-css/assets/6951585/d57c597e-ecef-41da-8b72-d2e64c9bef21" width=300>

Cheers!

**Comment by protomorphine** [comment]
I think I have the same issue
![image](https://github.com/jothepro/doxygen-awesome-css/assets/6265637/4445b1eb-a25c-4ce5-a496-c857fe0e83fd)
![image](https://github.com/jothepro/doxygen-awesome-css/assets/6265637/b49c6347-80cc-436c-8f53-0acecccde7f7)
![image](https://github.com/jothepro/doxygen-awesome-css/assets/6265637/f5a763cd-4940-4b75-86ef-52ebe6f814c0)

Doxygen 1.10.0
My [Doxyfile](https://github.com/protomorphine/ImmutableAnalyzer/blob/a70ae56ae1a506bf5efe62f1308440d3fefa6606/doc/Doxyfile)

**Comment by LDprg** [comment]
Same problem on Doxygen 1.10.0.

**Comment by jothepro** [comment]
Thx for reporting! This should be fixed in https://github.com/jothepro/doxygen-awesome-css/commit/c4a2f644a05af4242c6b4c171601a11daa3850d3.
