### ISSUE TITLE
[1.4.0] Fragment line height set to 0 by obsolete class

### ISSUE THREAD

**Issue by r0ckarong** [jothepro/doxygen-awesome-css#14]
https://github.com/jothepro/doxygen-awesome-css/blob/main/doxygen-awesome.css#L882

The line height is then overruled by setting the individual lines' height with the new variable a few lines further down. Is there a special reason the line height is first set to 0 for the fragment and then the lines are set to something else?

**Comment by jothepro** [comment]
```
div.fragment {
    line-height: 0;
}
```
([L883](https://github.com/jothepro/doxygen-awesome-css/blob/main/doxygen-awesome.css#L883)) sets the line height of the fragment container for fragments that define a span for each line, while 
```
div.fragment .line, pre.fragment {
    line-height: var(--fragment-lineheight);
}
```
([L893](https://github.com/jothepro/doxygen-awesome-css/blob/main/doxygen-awesome.css#L893)) sets the line height for the separate lines & `pre` fragments, which are fragments without separate spans for each line. So I don't see anything being overriden here. Am I missing sth?

**Comment by jothepro** [comment]
<img width="500" alt="Bildschirmfoto 2021-04-21 um 14 06 13" src="https://user-images.githubusercontent.com/21294002/115550968-bd5c1280-a2aa-11eb-866f-9353a2b256f4.png">

I hope this image helps to understand whats going on:

- L883 sets the green line height to 0, so there is no spacing between the diffs.
- L893 sets the blue line height, which is the real spacing between text lines.

**Comment by jothepro** [comment]
As I am looking at my own drawing I am starting to realize that my idea of a line height may be a bit wrong, as it is not equivalent with the space between lines. The key problem was that the line heights of the `.line` divs and the fragment added up somehow, which lead to the huge space between lines that you also observed in #9 .

**Comment by jothepro** [comment]
I removed the obsolete `line-height: 0` override. This will be included in the next release.
