### ISSUE TITLE
Works ok with Doxygen 1.12?

### ISSUE THREAD

**Issue by winterz** [jothepro/doxygen-awesome-css#159]
Question: has anyone tested with doxygen 1.12?
if so and it works ok, I think you can change the README to say  "🥇 Works best with doxygen 1.9.1 - 1.9.4 and 1.9.6 - 1.12.0"

**Comment by jothepro** [comment]
I've checked and at a first glance it seems to work fine with both 1.11.0 and 1.12.0. I've updated the README in 4593c198030b6e5019aae4d9c2eeb7497f02dbf8 👍
