### ISSUE TITLE
No search box found after using doxygen-awesome-css v1.4.0

### ISSUE THREAD

**Issue by zchrissirhcz** [jothepro/doxygen-awesome-css#21]

**Comment by zchrissirhcz** [comment]
doxygen version: 1.8.17
doxygen-awesome-css version: v1.4.0

**Comment by zchrissirhcz** [comment]
Tried with base theme, no search box shown.
Tried with side bar theme, no search box shown.
So weird.

**Comment by r0ckarong** [comment]
Stupid question: Did you turn the searchengine on in the doxyfile?

**Comment by zchrissirhcz** [comment]
I didn't change searchengine in Doxyfile, I think it should be default to yes. And now I apt remove that version doxygen, replaced with manually installed doxygen 1.9.2 (the latest), which shows search box.

**Comment by zchrissirhcz** [comment]
To be precise, I didn't know there is searchengine option keyword in Doxyfile until you mention it.
I use another ubuntu 16.04 mahine, apt install doxygen whose version is 1.8.11.  I see its default value is yes.

**Comment by jothepro** [comment]
The searchbox html structure has changed from doxygen 1.8 to 1.9.
doxygen-awesome-css currently only supports the 1.9 searchbox. I think it is not possible to support both versions at the same time, but I am open for a PR to fix this 🤔

**Comment by jothepro** [comment]
I am closing this issue since from my point of view it works as expected. If you can get the searchbox to work on both 1.8 & 1.9 pls share your changes with me! Thx :)
