### ISSUE TITLE
Bugs header menus colors

### ISSUE THREAD

**Issue by TheRolfFR** [jothepro/doxygen-awesome-css#22]
Hey,

Nice work, my doc is now looking sweet!

The header background foreground doesn't really like when we change the page foreground values.
For now I only changed the #top background and foreground but couldn't do more because you use the page color variables.

It messes with the chevron for because the text menu color is the page foreground color:
![image](https://user-images.githubusercontent.com/18086786/120167495-1a2ddf80-c1fe-11eb-93bd-a0fe675c1963.png)
When the chevron color is the header foreground:
![image](https://user-images.githubusercontent.com/18086786/120168018-b6f07d00-c1fe-11eb-826b-bfdea720c03c.png)
And because I set a dark background and a light foreground, we cannot see the chevron:
![image](https://user-images.githubusercontent.com/18086786/120168234-f15a1a00-c1fe-11eb-8c89-8c36f6d69414.png)
I had to set the border color to the foreground color so that I can see them:
![image](https://user-images.githubusercontent.com/18086786/120168432-1ea6c800-c1ff-11eb-8a38-626ca413cd1a.png)
But that doesn't work that well with hover:
![image](https://user-images.githubusercontent.com/18086786/120169592-67ab4c00-c200-11eb-821d-60391e89f655.png)
I fixed it with this piece of code base on the hover a color:
![image](https://user-images.githubusercontent.com/18086786/120171548-7266e080-c202-11eb-90be-34afa1bdaa13.png)
![image](https://user-images.githubusercontent.com/18086786/120171819-ba860300-c202-11eb-8bd6-419f53b6309e.png)

Could it be possible to add hover menus customization? For chevrons, border-color, box-shadow color?
![image](https://user-images.githubusercontent.com/18086786/120169375-2c108200-c200-11eb-9067-2c5b5f24c71e.png)

That could allow me to have a full dark top menu.
Thanks in advance!

**Comment by jothepro** [comment]
> Could it be possible to add hover menus customization?

Sure, that sounds like a good idea!

Btw I like the color-combination of your theme! Would you like to post it [here](https://github.com/jothepro/doxygen-awesome-css/discussions/13) so others can use it, too?

This would also help me to find out what variables are required to cover your customization requirements :)

**Comment by jothepro** [comment]
In the latest commit https://github.com/jothepro/doxygen-awesome-css/commit/072e779b1aa0ad298b2410882c392feb8b0fae5c I have set the sub-arrow color to `--page-foreground-color` instead of `--header-foreground`. Pls let me know if that fixes the issue for you. 

While this does not give you the full customization control that you asked for, a dark header with white text should now be possible.
