### ISSUE TITLE
Possible to always show the foldout triangle in side bar? 

### ISSUE THREAD

**Issue by justin-pierce** [jothepro/doxygen-awesome-css#24]
Unlike the default Doxygen theme, Awesome only shows the foldout triangles if you hover over that particular element. Is there a quick way to change that behavior to always show? 

Thanks,

**Comment by r0ckarong** [comment]
This is one of the first things I wanted to fix with my theme. 

You need to create an override for the opacity of the "arrow" (which is the triangle).

Like this:

```
#nav-tree .arrow {
  opacity: 1;
}
```

I did this in a second CSS file that contains all my extra styles that deviate from the base theme from here.
I think you can just change/add this in the doxygen-awesome.css file but this isn't update proof.

@jothepro 
I think this actually should be a theme option mentioned in the readme, "do you want to have the navtree icons shown permanently or not". (I personally have no idea why you would hide them tbh).

**Comment by jpgarza93** [comment]
I also added some CSS to change it. I liked being able to see the arrows at all times, but I didn't want them to grab a lot of attention. Therefore, I made them smaller and kept a small opacity value:

`
/*--- NAV TREE ---*/
.arrow:hover {
    opacity: 1 !important;
}
.arrow {
    opacity: 0.25 !important;
    color: inherit;
    cursor: pointer;
    font-size: 45%;
    vertical-align: middle;
    margin-right: 3.5px;
}
`

See my documentation here: https://rapidcode.roboticsys.com/

**Comment by justin-pierce** [comment]
Thanks for all the responses! Worked like a charm!

**Comment by jothepro** [comment]
FYI: I have added the new variables `--side-nav-arrow-opacity` &  `--side-nav-arrow-hover-opacity` that make the arrow opacity in the sidebar configurable and I adopted the beautiful arrow style by @jpgarza93 in this commit: https://github.com/jothepro/doxygen-awesome-css/commit/20d9586642ff3aba0b7814f26c8f2012fbfc4373

Pls let me know if that helps you to reduce your manual overrides. This will be included in a new release in the next days. :)
