### ISSUE TITLE
`DISABLE_INDEX  = YES` is not supported: The MSearchBox is too close to the title

### ISSUE THREAD

**Issue by Nambers** [jothepro/doxygen-awesome-css#25]
This theme is awesome, but i think the MSearchBox is too close to the title, like this picture showed:
![image](https://user-images.githubusercontent.com/35139537/122598193-15db4080-d09f-11eb-8bd1-a5faf89fdd25.png)
I believe we should add a margin-left to css, such as `margin-left: 2vw`. It will look better, like this:
![image](https://user-images.githubusercontent.com/35139537/122598322-428f5800-d09f-11eb-8143-5bc41347659a.png)

**Comment by jothepro** [comment]
Can you give me some details about your Doxygen configuration? It seems like you are using the doxygen-awesome base theme, but have the top menu disabled? Normally the menu in the titlebar should push the searchbar to the right, it's not supposed to stick to the logo like this 🤔

**Comment by Nambers** [comment]
okok, that is odd, and i seen your demo donnot have this kind of problem. I donnot have logo yet
[Doxyfile.txt](https://github.com/jothepro/doxygen-awesome-css/files/6679831/Doxyfile.txt)

**Comment by Nambers** [comment]
And also, if i use sidebar, it look like this:
![image](https://user-images.githubusercontent.com/35139537/122630327-46e66000-d0f5-11eb-91a5-e2f76dd5396b.png)

**Comment by jothepro** [comment]
The problem is with 
```
DISABLE_INDEX          = YES
```

It seems like this breaks the layout, because the titlebar menu that pushes the searchbar to the right is not generated. I'll rename this issue accordingly. I consider this a bug, but I'm not sure if I will find time to fix it anytime soon.

I'd recommend you to set `DISABLE_INDEX = NO` to fix your page layout for now.

**Comment by Nambers** [comment]
okok, when i set it to "no", the problem fixed.
thx

**Comment by Nambers** [comment]
I think this problem may not necessary to fix.
