### ISSUE TITLE
DOT-Graphs for color-scheme dark

### ISSUE THREAD

**Issue by bernd1995** [jothepro/doxygen-awesome-css#27]
First of all, thanks for this really nice css theme. 
It makes the look of a doxygen documentation really a lot better.

However I have a short remark. It would be nice if you could add a short hint somewhere in the documentation, about using DOT-Graphs combined with the dark color-scheme. Because it is necessary to set the `DOT_TRANSPARENT` value in the Doxyfile to `YES` for nice graphs without some black background. Otherwise the color of the graph is changed by `filter: hue-rotate(180deg) invert();` which makes the white background black, which however does not blend in with the background in dark-mode.

Spent almost an eternity to find out what's wrong with my output. 😅 

As a future possibility without relying on `DOT_TRANSPARENT`: I guess it would also be possible to add some `javascript` function to edit the graph-colors which may circumvent the documented problems of the dot-transparent setting (see [here](https://www.doxygen.nl/manual/config.html#cfg_dot_transparent)). Additionally this would add the possibility to change also the colors of the arrows in the graphs depending on `--primary-color` for instance and so on.

**Comment by bernd1995** [comment]
Just saw that you've updated the README.md. 
Thanks :smile: 

I guess I can close the issue now?

**Comment by jothepro** [comment]
Yep, fixed in https://github.com/jothepro/doxygen-awesome-css/commit/8739758d46602cf90e95e349731faa2ea7109d8d

Thanks for reporting the bug!
