### ISSUE TITLE
Menu runs over content 

### ISSUE THREAD

**Issue by Warchant** [jothepro/doxygen-awesome-css#3]
If you use doxygen-awesome-css as-is, on mid-size screen devices menu will run over content:
![image](https://user-images.githubusercontent.com/1867551/112623852-89213d80-8e35-11eb-9a6d-a91150a45214.png)

Here is the fix:
```
@media screen and (min-width: 767px) and (max-width: 1410px) {
    #doc-content .contents, #doc-content .header .title {
        margin-left: 250px;
    }
}
```

**Comment by jothepro** [comment]
I can not reproduce that. Something seems odd about your treeview navigation. Normally the `margin-left` of `#doc-content` is set dynamically by javascript. Can you provide the Doxyfile and the Doxygen version you used for generation? Do you have Javascript enabled?

**Comment by Warchant** [comment]
1. Repo: https://github.com/VeriBlock/alt-integration-cpp/ - Doxyfile is in the root directory.
2. Deployed: https://veriblock.github.io/alt-integration-cpp/ 

Here is my fix: https://github.com/VeriBlock/alt-integration-cpp/blob/master/docs/look/main.css#L24-L28, you can try to comment it.

To generate and view docs:
1. clone repo
2. mkdir build
3. doxygen
4. browser build/docs/html/index.html

**Comment by Warchant** [comment]
Also, if I use 
```
HTML_DYNAMIC_MENUS     = NO
```

Styles for top menu are from original doxygen theme:
![image](https://user-images.githubusercontent.com/1867551/112645506-36ed1600-8e4f-11eb-937f-0119a3726653.png)

**Comment by jothepro** [comment]
Hm. When I first visited your website a few hours ago, there where Javascript errors in the console that clearly where the issue why the left margin wasn't set correctly. This seems to be resolved now. Did you change anything? It seems to me that you can now remove your fix that sets a fixed `margin-left`.

But now somehow the height of the treeview seems to be broken. It should be set by the treeview javascript as well:

- On my setup: The width and height of the side-nav are calculated by some javascript magic and set as absolute values:
<img width="1439" alt="Bildschirmfoto 2021-03-26 um 19 55 18" src="https://user-images.githubusercontent.com/21294002/112680585-d9b48d00-8e6d-11eb-8d55-7f0a252cbfca.png">

- On your website: Somehow only the width is being set. I am also missing the footer with it's navigation breadcrumps. Maybe the sidenav needs the footer to be able to calculate it's height proprely?
<img width="1439" alt="Bildschirmfoto 2021-03-26 um 19 56 15" src="https://user-images.githubusercontent.com/21294002/112680615-e1743180-8e6d-11eb-870e-ee8b2a584d22.png">

I am not going to investigate this further as it seems to be an issue that's not related to the custom css. I'm sure that the side-nav would be broken with the default theme as well.

---

Thanks for the tip with the top menu when setting `HTML_DYNAMIC_MENUS     = NO`!
Furthermore, when browsing your site I found out that I should support `@invarint` and `@pre` (#4 )

I will fix these 2 things. Stay tuned! Your contribution would be welcome as well! :)

Please make sure to update to my latest release ([v1.2.2](https://github.com/jothepro/doxygen-awesome-css/releases/tag/v1.2.2)) to get improvements for dark-mode, code-fragments and lots of optimizations for small screens! :)

**Comment by Warchant** [comment]
@jothepro thanks for your time.
You do not see a footer, because I am using custom footer.html, which has single <script>. I did this to inject my JS script to improve diffs:
![image](https://user-images.githubusercontent.com/1867551/112722506-a710a000-8f12-11eb-9913-90a50eb6ee1d.png)

I think original footer contains some style/js which fixes this behavior... Will dig into that.

**Comment by jothepro** [comment]
FYI `HTML_DYNAMIC_MENUS = NO` is now supported. I'm not confident that it works well with the minimalistic look of this theme, but at least it blends in better with the rest of the theme now.

Check it out in release [v1.3.0](https://github.com/jothepro/doxygen-awesome-css/releases/tag/v1.3.0)
