### ISSUE TITLE
dark mode toggle have 0x0 size

### ISSUE THREAD

**Issue by Nambers** [jothepro/doxygen-awesome-css#32]
Hi,
**problem**
When I apply the dark mode toggle to my website, the toggle hide:
![image](https://user-images.githubusercontent.com/35139537/124339406-e79e4a80-dbe0-11eb-9a09-eba6ddf5e45f.png)

And the css file loaded normally in the page:
![image](https://user-images.githubusercontent.com/35139537/124339429-0e5c8100-dbe1-11eb-85ac-4f2073c5e1db.png)

**additional question**
The doc in readme may no clear enough, I think u mean add those line into default css(generated by doxygen)?
When i take my first eye on it, I just copy those content to footer.html and header.html.(And undoubtedly the website cannot work well).

And the generate command of doxgen(1.9.1) should be 3 arguments (like `doxygen -w html header.html footer.html _` and del the '_' file), but in doc there just 2 arguments

thx

**Comment by Nambers** [comment]
Doxygen file:
[Doxyfile.txt](https://github.com/jothepro/doxygen-awesome-css/files/6757675/Doxyfile.txt)

**Comment by jothepro** [comment]
The toggle by default is a custom element with no styling at all. That's why it has size 0x0.
You have to update the `doxygen-awesome.css` as well, it comes with the required styles.

Thanks for pointing out that the `doxygen -w` command in the Readme is wrong. I've corrected that in https://github.com/jothepro/doxygen-awesome-css/commit/feec51089fd2bc863018e560d93455baec42381a.

**Comment by jothepro** [comment]
> The doc in readme may no clear enough

One of the reasons why I haven't added this feature earlier is because the setup is not as trivial as I'd like it to be. If you struggled with the documentation and have ideas on how it can be improved, pls share them with me by opening a PR! :)

**Comment by Nambers** [comment]
> The toggle by default is a custom element with no styling at all. That's why it has size 0x0.
> 
> You have to update the `doxygen-awesome.css` as well, it comes with the required styles.
> 
> 
> 
> Thanks for pointing out that the `doxygen -w` command in the Readme is wrong. I've corrected that in https://github.com/jothepro/doxygen-awesome-css/commit/feec51089fd2bc863018e560d93455baec42381a.

oh yes，my other css files is the old version
i will try this later
thx

**Comment by Nambers** [comment]
This problem fixed by that solution, now it work well in my website(https://eritque-arcus.tech/MiraiCP/html/index.html).

That great.( well done :D
thx
