### ISSUE TITLE
In the default dark mode, the "Class Index" table style uses a hard to read background color.

### ISSUE THREAD

**Issue by Jimmacle** [jothepro/doxygen-awesome-css#5]
Hey there, thanks for making this so my documentation doesn't look like it was published in the 90s. I've noticed a problem with the default dark theme where the class index uses a super white background color on every other row of the list:
![image](https://user-images.githubusercontent.com/6447556/113496779-e8c0be00-94b1-11eb-8723-d99c61c34fa5.png)

I think it would be much easier to read if it used a gray background instead of the white like here:
![image](https://user-images.githubusercontent.com/6447556/113496795-0857e680-94b2-11eb-9662-f18e728e1864.png)

The live page where I'm seeing this issue is here if that helps: https://apeira.github.io/Torch/classes.html

**Comment by jothepro** [comment]
Thanks for reporting! I will fix this in the next release.

**Comment by jothepro** [comment]
Pls resolve if release [v1.3.0](https://github.com/jothepro/doxygen-awesome-css/releases/tag/v1.3.0) fixes this for you.

**Comment by Jimmacle** [comment]
Confirmed fixed, thanks for the update.
