### ISSUE TITLE
Black background on iframes (graphics, search) in dark mode

### ISSUE THREAD

**Issue by jothepro** [jothepro/doxygen-awesome-css#51]
On Chrome 94 all elements embedded in iframes (e.g. dependency graphs, search results) do **sometimes** have a black background:
<img width="468" alt="Bildschirmfoto 2021-10-08 um 19 30 29" src="https://user-images.githubusercontent.com/21294002/136598922-3ca5af96-421f-43d9-a12c-10c26e4878cc.png">

## How to reproduce

- Make sure the system does not have dark-mode enabled
- Go to a page in the example docs containing a dependency graph (e.g. [here](https://jothepro.github.io/doxygen-awesome-css/class_my_library_1_1_example.html))
- Enable dark mode by clicking the <kbd>☀️</kbd>-Button
- the background of the graphs should be fine:
   <img width="468" alt="Bildschirmfoto 2021-10-08 um 19 37 33" src="https://user-images.githubusercontent.com/21294002/136599507-53f83370-500d-4c6e-9550-0fd3e832b460.png">
- refresh the page 
- now the iframe-background is not transparent any more and it will stay black on all iframes. 😲 

I can  reproduce this on  Chrome 94 on macOS and on Chrome for Android. Other [supported browser](https://github.com/jothepro/doxygen-awesome-css#browser-support) don't seem to be affected. I don't know when this started to be a problem and I don't know what the reason might be.

Given the fact that it is not consistent (it only starts to be a problem after a page refresh or if the page is loaded in dark mode) even let's me consider that this might be a bug in Chrome?

If you want to help, pls let me know if you can reproduce the issue or if you have an idea what is going on... 🤔

**Comment by dmadison** [comment]
I can reproduce this. Chrome 94.0.4606.81 on Windows using the link in your comment. Disabling the `color-scheme: dark` property seems to fix it? E.g.:

```css
iframe {
    color-scheme: normal;
}
```

Although I'm just testing in the page inspector and a page refresh may show the issue again.

I found [this article](https://dev.to/bcalou/the-trouble-with-chrome-iframes-and-mix-blend-mode-4bi1) which has some insights about iframes and transparency bugginess in Chrome. It may explain what's going on.

**Comment by jothepro** [comment]
I can confirm that this fixes the problem! Thank you so much, I'd never would have found this!
This will be included in the upcoming 1.6.1 patch release: https://github.com/jothepro/doxygen-awesome-css/commit/c52f8129d0c8f21d5f4d9d099a3e158f98483dbe
