### ISSUE TITLE
Dark Mode toggle broken in Doxygen 1.9.2

### ISSUE THREAD

**Issue by jothepro** [jothepro/doxygen-awesome-css#52]
@dmadison reported in #47:  On mobile [...] the dark mode toggle runs off the screen. When testing in Chrome using the device toolbar, the dark mode toggle also disappears after resizing (and reappears on refresh).

**Comment by dmadison** [comment]
Thanks for looking into this. I've just tested with that snippet and the toggle is in its proper place and persists on window resize. Although when resizing down to mobile width on desktop the toggle still drops down below the search bar. My guess is that the width of the vertical scroll bar is not accounted for somewhere.
