### ISSUE TITLE
Feature Request - force dark/light mode

### ISSUE THREAD

**Issue by higaski** [jothepro/doxygen-awesome-css#54]
It would be great if dark or light mode could be enforced somehow independently of the system preferences. 
Transparency or not, having a project with a lot of images from dot or mscgen simply looks better in light mode.

**Comment by jothepro** [comment]
I've figured out that it is enough to just add the class `light-mode` to the html tag in the header template:

```html
<html xmlns="http://www.w3.org/1999/xhtml" class="light-mode">
```

This disables the dark mode permanently without the need to modify `doxygen-awesome.css`.
It seems like I already accidentally implemented the requested feature, without knowing. 🙈 

Disclaimer: This only works if you don't use the [dark-mode toggle extension](https://jothepro.github.io/doxygen-awesome-css/md_docs_extensions.html#autotoc_md15).

**Comment by higaski** [comment]
Wahaha that's great. Feature by accident. Thank you! :)

**Comment by jothepro** [comment]
I've added documentation about how to force light-/dark-mode [here](https://jothepro.github.io/doxygen-awesome-css/md_docs_tricks.html#autotoc_md27)

If you run into problems with this approach, pls let me know!

**Comment by higaski** [comment]
More recent firefox version (at least 107.0) seem to break that feature for whatever reason. :(

Here is a comparison with Chromium 107.0.5304.110
![chromium_firefox](https://user-images.githubusercontent.com/13762516/202521204-b3e12652-57f5-461b-bd00-165090fb0562.png)
