### ISSUE TITLE
Sidebaronly version not working.

### ISSUE THREAD

**Issue by Frozen71** [jothepro/doxygen-awesome-css#55]
I tried to implement the sidebar only theme but it didn't work.

**Comment by jothepro** [comment]
Pls share the following information with me:

- A link to the sources if you are allowed to share them publicly.
- if thats not possible: Your Doxyfile and/or a description of what you did to install the sidebar-only theme.

If you struggle on how to integrate the theme with your documentation, you may want to look at the demo implementation that is served [here](https://jothepro.github.io/doxygen-awesome-css/).
You can find the related Doxyfile and custom footer/header in this repository.

**Comment by Frozen71** [comment]
I solved my problem by modifying your demo project instead of creating a new one. I believe your tutorial is not clear. It would be great if you can add more detailed steps.
