### ISSUE TITLE
List of overwritable CSS-parameters

### ISSUE THREAD

**Issue by Zekkken** [jothepro/doxygen-awesome-css#58]
Hey there!

You showed some of the configurable CSS-parameters, but is somewhere out there a full list?

Best regards

**Comment by jothepro** [comment]
Did you resolve your problem with the searchbar being positioned oddly?

You can find a complete list of all defined CSS variables in the first `html` selector [here](https://github.com/jothepro/doxygen-awesome-css/blob/main/doxygen-awesome.css#L30) in the CSS  (L30-157).

The comments in the CSS and the list in the Readme is all documentation that's currently available.
You can also explore the list of defined variables in

**Comment by Zekkken** [comment]
Hey, thank you for the guidance :)
Yes, I resolved the oddly placed searchbar. It seemed like that the error resulted from the fact that my Doxyfile was from an old version of Doxygen or that something in it was broken. After I replaced it by a automatically generated one from Doxygen 1.9.1 it worked just fine!
