### ISSUE TITLE
Class list has too bright elements

### ISSUE THREAD

**Issue by tdegeus** [jothepro/doxygen-awesome-css#6]
Thanks once more for the great theme!

I was just looking under "Class Lists", and there I find really bright elements:

<img width="1395" alt="Screenshot 2021-04-07 at 08 54 35" src="https://user-images.githubusercontent.com/7030445/113823711-44739b80-977f-11eb-9635-5b8a0656c402.png">

Personally I find this a bit tough on the eyes, and difficult to read. 
Is there something that could be done?

**Comment by jothepro** [comment]
I'm proud to tell you that this has already been fixed in the brand new release [v1.3.0](https://github.com/jothepro/doxygen-awesome-css/releases/tag/v1.3.0).

Pls re-open if it is still a problem after you updated.

**Comment by tdegeus** [comment]
Thanks!
