### ISSUE TITLE
Feature suggestion: collapse/fold code blocks

### ISSUE THREAD

**Issue by nilsvu** [jothepro/doxygen-awesome-css#64]
I think it could be quite useful to add a "fold code block" feature. We could annotate a code block as "folded" in Doxygen somehow, and then hide it behind a `>` indicator that can be clicked to reveal the code. Jupyter notebooks have this feature, and ReadTheDocs too: https://sphinx-toolbox.readthedocs.io/en/stable/extensions/collapse.html#directive-collapse. You can even do this in GitHub markdown using the `<details>` tag:

<details>
  <summary>Click to expand</summary>
  Hello!
</details>

**Comment by jothepro** [comment]
Closing the issue because this is now supported in Doxygen 1.9.5
