### ISSUE TITLE
font load delay

### ISSUE THREAD

**Issue by nazmi** [jothepro/doxygen-awesome-css#67]
Not sure if this is Doxygen or the CSS problem. The page loaded as expected on the desktop environment, but not on the tablet. Fonts are loaded when there is interaction with the browser, like scrolling to the end.

https://user-images.githubusercontent.com/524301/159328484-6c7638b2-41fe-4ea1-b946-64c2467a7c7e.mp4  

  
Doxygen.cfg
```bash
GENERATE_HTML           = YES
GENERATE_XML            = NO
GENERATE_LATEX          = NO
HAVE_DOT                = YES
DOT_IMAGE_FORMAT        = svg
DOT_TRANSPARENT         = YES

# Project Stuff
PROJECT_NAME           = "EEEN21000"
PROJECT_BRIEF          = "GROUP 30 Line Following Buggy"
OUTPUT_DIRECTORY       = ""

# Inputs
INPUT                  = README.md \ 
                      

RECURSIVE              = YES

EXTRACT_ALL            = YES
EXTRACT_PRIVATE        = YES
EXTRACT_PRIV_VIRTUAL   = NO
EXTRACT_PACKAGE        = NO
EXTRACT_STATIC         = YES
EXTRACT_LOCAL_CLASSES  = YES
USE_MATHJAX            = YES
SORT_MEMBER_DOCS       = NO
USE_MDFILE_AS_MAINPAGE = README.md

GENERATE_TREEVIEW      = YES
HTML_HEADER            = header.html
HTML_EXTRA_FILES     = doxygen-awesome-css/doxygen-awesome-darkmode-toggle.js \ 
                         doxygen-awesome-css/doxygen-awesome-paragraph-link.js \
HTML_EXTRA_STYLESHEET  = doxygen-awesome-css/doxygen-awesome.css \
                         doxygen-awesome-css/doxygen-awesome-sidebar-only.css \ 
                         doxygen-awesome-css/doxygen-awesome-sidebar-only-darkmode-toggle.css                  
```

**Comment by jothepro** [comment]
Hmm, thats weird. There is no external font loading, the doxygen-awesome-css theme (like the original Doxygen theme) is only defining a list of [preferred system fonts](https://github.com/jothepro/doxygen-awesome-css/blob/main/doxygen-awesome.css#L63) that the browser can choose from. So I cannot imagine how a delay like this could happen. 🤷 

I'll keep this issue open for a while though, maybe someone else can help?

**Comment by nazmi** [comment]
Works fine now, I think this might be random behaviour. Possibly browser.
