### ISSUE TITLE
Inheritance graph legend link is not colored like a link

### ISSUE THREAD

**Issue by r0ckarong** [jothepro/doxygen-awesome-css#8]
Below the inheritance diagrams there is a small span containing the word "legend". This leads to a generated page explaining the colors used in the diagram.

![image](https://user-images.githubusercontent.com/4920542/115001711-30791980-9ea4-11eb-955c-341c6d6ec572.png)

When this has been visited before, this link is styled with some weird color (#300000) and doesn't stand out. 

![image](https://user-images.githubusercontent.com/4920542/115003443-17716800-9ea6-11eb-8d59-f4dcfa45972b.png)

This can be overridden by setting something like

```
.contents a:visited {
  font-color: var(--primary-dark-color);
}
```
![image](https://user-images.githubusercontent.com/4920542/115003564-37a12700-9ea6-11eb-8921-12eb1a09af06.png)

I'm not entirely sure what is going on there and why the declared style for anchors doesn't apply in this case.

**Comment by jothepro** [comment]
The legend-link does not exist in my [example classes](https://jothepro.github.io/doxygen-awesome-css/class_my_library_1_1_subclass_example.html) for testing. Do you know what the precondition is for them to show up?

**Comment by r0ckarong** [comment]
From what I can tell this one comes from the LWIP_INIT_PARAM_T is a struct that contains the const LWIP_MEMORY_POOL_CFG_T and defines the pointer ptMemoryPoolCfg. So that's why it "uses" (dashed purple arrow) the 

```
typedef struct {
[...] other stuff

  const LWIP_MEMORY_POOL_CFG_T   *ptMemoryPoolCfg;
} LWIP_INIT_PARAM_T;
```

The legend definition is here:

```
/*! Invisible class because of truncation */
class Invisible { };
/*! Truncated class, inheritance relation is hidden */
class Truncated : public Invisible { };
/* Class not documented with doxygen comments */
class Undocumented { };
/*! Class that is inherited using public inheritance */
class PublicBase : public Truncated { };
/*! A template class */
template<class T> class Templ { };
/*! Class that is inherited using protected inheritance */
class ProtectedBase { };
/*! Class that is inherited using private inheritance */
class PrivateBase { };
/*! Class that is used by the Inherited class */
class Used { };
/*! Super class that inherits a number of other classes */
class Inherited : public PublicBase,
protected ProtectedBase,
private PrivateBase,
public Undocumented,
public Templ<int>
{
private:
Used *m_usedClass;
};

```

![image](https://user-images.githubusercontent.com/4920542/115014397-92408000-9eb2-11eb-9f7b-795aac115372.png)


![image](https://user-images.githubusercontent.com/4920542/115014371-88b71800-9eb2-11eb-81ab-864821eb7cb9.png)

Maybe this'll help building more examples? Honestly I am pretty new to C++ and don't understand much of that.

**Comment by jothepro** [comment]
I have fixed some link coloring inconsistencies in this commit: https://github.com/jothepro/doxygen-awesome-css/commit/072e779b1aa0ad298b2410882c392feb8b0fae5c

Pls let me know if that fixes the "legend" link color as well. :)

**Comment by jothepro** [comment]
I've tested it myself and it seems like this is resolved. Pls re-open if you disagree.
