### ISSUE TITLE
Feature request: ToC as side bar

### ISSUE THREAD

**Issue by leissa** [jothepro/doxygen-awesome-css#81]
Would be really cool to have an option to render the ToC on the right hand side of the main area similar to this:
https://rise-lang.org/doc/language-reference/rise-types/

Right now, the ToC box is quite small and headers are often broken into several lines - which makes the ToC box a bit harder to read. Furthermore, the ToC shrinks the space for code boxes and the "Copy to Clipboard" button isn't visible. Finally, having a ToC box anchored on the top right would also enhance the overall reading/navigation experience.

**Comment by Becheler** [comment]
Hi @jothepro ! Any news on this (amazing) feature and maybe a planned release date?

**Comment by jothepro** [comment]
The feature has already been released with [v2.1.0](https://github.com/jothepro/doxygen-awesome-css/releases/tag/v2.1.0)

I'll close this issue to avoid confusion.

**Comment by leissa** [comment]
Great work. Love it :)
