### ISSUE TITLE
Scrollbars look bad with Doxygen v1.9.5

### ISSUE THREAD

**Issue by nilsvu** [jothepro/doxygen-awesome-css#86]
Doxygen v1.9.5 added some webkit scrollbar styling that conflicts with the doxygen-awesome style: https://github.com/doxygen/doxygen/commit/260f2fadf8b780d824cba2e490d119e759ada101

If it's unclear what's broken I'm happy to add some screenshots, but I think it's quite obvious when looking at a generated page, at least on macOS Safari in dark mode.

**Comment by jothepro** [comment]
I've been struggling with the same problem today. Unfortunately it seems like I cannot patch this with pure CSS. 🙁

https://github.com/doxygen/doxygen/issues/9549

**Comment by jothepro** [comment]
As a quick workaround you could maybe modify `doxygen.css` and remove the lines that define the scrollbar style: https://github.com/doxygen/doxygen/commit/260f2fadf8b780d824cba2e490d119e759ada101

**Comment by jothepro** [comment]
Doxygen 1.9.6 is out and has resolved this issue. Pls consider upgrading to this version, Doxygen 1.9.5 is still not supported by this theme!
