### ISSUE TITLE
Centering a table with `<center>` cuts off the border of the table

### ISSUE THREAD

**Issue by jothepro** [jothepro/doxygen-awesome-css#91]
As reported in #88, a table can not be centered with the `<center>` html tag, because then the left and right borders of the table will be cut of on small screens (when the table covers the full width of the content):

<img width="495" alt="Bildschirmfoto 2022-10-02 um 14 25 55" src="https://user-images.githubusercontent.com/21294002/193453819-17dcd674-fe59-449c-ae6b-a8286c49fd2a.png">

**Comment by MuellerSeb** [comment]
As mentioned, this hack solved it for me:
```css
table{
  padding:1px;
}
```
But still, the table content is centered as well in each cell. I don't know if it is desired that way, but I wouldn't say so.

**Comment by jothepro** [comment]
I've added your workaround to the latest release [v2.2.0](https://github.com/jothepro/doxygen-awesome-css/releases/tag/v2.2.0). The table should not be cut off now.
