### ISSUE TITLE
add support for MD file as the main page

### ISSUE THREAD

**Issue by peterlauro** [jothepro/doxygen-awesome-css#94]
would it be possible to provide a support of MD (markdown) file as the main page?

https://www.doxygen.nl/manual/config.html#cfg_use_mdfile_as_mainpage.

it can be usefull also in the case when the doxygen project documentation is generated from the cmake scope. The project specific cmake configuration file can assigned the corresponding MD file as the start page.
https://cmake.org/cmake/help/latest/module/FindDoxygen.html?highlight=doxygen#command:doxygen_add_docs

- probably it's supported already

**Comment by jothepro** [comment]
Can you elaborate in more detail what you mean? This is actually what I do [in the example documentation](https://jothepro.github.io/doxygen-awesome-css/). The main page is the README.md from the repository: https://github.com/jothepro/doxygen-awesome-css/blob/main/Doxyfile#L1069

**Comment by peterlauro** [comment]
I have seen your configuration, that's the reason why I made the comment "probably it's supported already". I guess my issue is that Doxyfile.cfg is on different level of directory hierarchy as README.md. Let me do some tests tomorrow.

**Comment by jothepro** [comment]
I am assuming that your question has been answered? Feel free to re-open the issue if I was mistaken!
