### ISSUE TITLE
How to add a note in a markdown doc file?

### ISSUE THREAD

**Issue by Becheler** [jothepro/doxygen-awesome-css#98]
Hi! 
I am pretty I've seen note blocks being displayed nicely, I guess when I use the annotation @note in a code comment.
Is there a way to do the same formatting inside an extra page of documentation in markdown format?
The only way I can achieve something similar is using the classical quote block, but it's rendered as a quote, where I would for example want a warning, an announcement etc ...
```
> This is 
> about it.
```

**Comment by jothepro** [comment]
I've never tried that, but it's an interesting question! 
Doxygen commands like `@note` seem to work in the main page (`USE_MDFILE_AS_MAINPAGE = README.md`), but not in other markdown documents (based on my experiments). 

You may want to ask this question in [doxygen/doxygen](https://github.com/doxygen/doxygen).

If it's not a priority to you that the document is a markdown file, I think you could always add doxygen documentation pages like in this [example](https://github.com/CGAL/cgal/blob/master/Documentation/doc/Documentation/Tutorials/Tutorial_hello_world.txt).

**Comment by Becheler** [comment]
Thank you for your timely answer!
Actually, you solved my problem: there is no fancy syntax or formatting, just:
```
@note
This is a note
```
Gets properly displayed, even in a non-main page, and it seems to work with note, warning, attention etc ... Interesting! :D thank you!
