### ISSUE TITLE
Color scheme suddenly broke?

### ISSUE THREAD

**Issue by Becheler** [jothepro/doxygen-awesome-css#99]
Hi again 👋🏽 

I wanted to add the Github corner from https://github.com/tholman/github-corners , so I added the snippet to the `header.hml`, had some troubles fixing a problem with page/subpages and some time later I began to notice a problem with the Doxygen-awesome night/light color scheme:

<img width="1271" alt="Screen Shot 2022-12-02 at 2 22 02 AM" src="https://user-images.githubusercontent.com/8360330/205273417-8cdf9256-0456-4ff7-8112-8435bd4a3363.png">
<img width="1271" alt="Screen Shot 2022-12-02 at 2 22 16 AM" src="https://user-images.githubusercontent.com/8360330/205273468-96c936d3-71e0-4088-8231-8d0e559b0f9f.png">

Any idea what I may have done to trigger this (and how to revert it if it is a known issue?)
Thanks!

**Comment by jothepro** [comment]
This looks somewhat familiar to me. Pls let me know if the information in #97 helps you to fix this.

**Comment by Becheler** [comment]
Yes it worked - I think!
Is it expected that the dark theme would have very bright white lines in tables? I find it difficult to read... Here are two views:
![Screen Shot 2022-12-02 at 11 56 35 AM](https://user-images.githubusercontent.com/8360330/205375554-a156bf65-33a4-4f3b-831f-07e1d6df1a55.png)
![Screen Shot 2022-12-02 at 11 55 57 AM](https://user-images.githubusercontent.com/8360330/205375557-ee744c5f-2fff-499b-ae15-5c3fb9b9b14a.png)

**Comment by jothepro** [comment]
Nope, this also doesn't look like it should, in both light and dark mode. I am pretty sure this also has to do with a doxygen 1.9.5 incompatiblity. I'll try to look into it asap, until then my advice would be to downgrade to 1.9.4 since 1.9.5 is not officially supported by this theme atm.

**Comment by jothepro** [comment]
Did you by any chance find a way to fix this problem? I tried to reproduce it but I had no luck so far.
If the problem still persists: Can you provide me some information about your Doxyfile configuration?

**Comment by Becheler** [comment]
I got lost in other stuff and just came back to this specific issue today seing your comment. 
The problem is gone and I don't know what fixed it 😓
But one thing is sure is that I upgraded to the last version of doxygen-awesome (v2.1.0) few days ago 🤔  
I will close this issue keeping in mind to add any update :) thanks again for your work man it's ... awesome ;)
